"""
Pydantic models for the Cognitive Loop Engine.

Validates all configuration and runtime data structures.
Inspired by OMO's Zod schema system (36 schema files) but using Pydantic for Python.
"""

from enum import Enum
from typing import Literal, Optional
from pydantic import BaseModel, Field


# --- Enums ---

class TaskState(str, Enum):
    """Pipeline states for a task. Mirrors the state machine in AGENTS.md."""
    BACKLOG = "backlog"
    PENDING_TRIGGER = "pending_trigger"
    PLANNING = "planning"
    AWAITING_APPROVAL = "awaiting_approval"
    IMPLEMENTING = "implementing"
    QA = "qa"
    REVIEW = "review"
    AWAITING_CLOSURE = "awaiting_closure"
    CLOSED = "closed"
    QA_REJECTED = "qa_rejected"
    CRASHED = "crashed"
    ABORTED = "aborted"


class ProviderPriority(BaseModel):
    """Priority-ordered model chain for a category."""
    models: list[str] = Field(..., min_length=1, description="Ordered fallback models: provider/model")
    reasoning: Optional[str] = Field(None, description="Reasoning level override")


class CategoryConfig(BaseModel):
    """Category-based model routing — ported from OMO's visual-engineering/deep/quick/ultrabrain."""
    models: list[str] = Field(..., min_length=1)
    reasoning: Optional[str] = None
    description: Optional[str] = None


class ProviderConcurrency(BaseModel):
    """Max concurrent requests per provider — prevents cost spiral."""
    anthropic: int = 3
    openai: int = 3
    opencode: int = 10
    zai: int = 10
    kimi: int = 5


class ApprovalConfig(BaseModel):
    """Telegram approval gateway settings."""
    bot_token_env: str = Field("TELEGRAM_BOT_TOKEN", description="Env var name for bot token")
    chat_id: int = Field(..., description="Telegram chat ID for Manager")
    timeout_seconds: int = 3600  # 1 hour to respond


class IdleConfig(BaseModel):
    """Auto-continue settings — inspired by OpenCode Goal Plugin's no-progress detection."""
    thinking_timeout_seconds: int = 60  # Phase 1: thinking (no bash running)
    executing_timeout_seconds: int = 900  # Phase 2: bash running (15 min)
    max_retries: int = 5
    no_progress_threshold: int = 50  # token threshold for no-progress
    no_progress_turns_before_pause: int = 2
    min_delay_seconds: float = 2.0  # cooldown between continue attempts


class StackDetectionConfig(BaseModel):
    """Heuristics for auto-detecting a stack profile."""
    marker_files: list[str] = Field(default_factory=list, description="Files whose presence implies this stack")
    extensions: list[str] = Field(default_factory=list, description="File extensions implying this stack (e.g. .py)")
    task_keywords: list[str] = Field(default_factory=list, description="Keywords in task content implying this stack")


class StackToolchainConfig(BaseModel):
    """Toolchain commands for a stack."""
    test_cmd: str | None = Field(None, description="Command to run tests for this stack")
    build_cmd: str | None = Field(None, description="Command to build this stack")
    lint_cmd: str | None = Field(None, description="Command to lint this stack")


class StackProfileConfig(BaseModel):
    """Declarative profile for a tech stack."""
    name: str = Field(..., description="Canonical stack name (matches filename without extension)")
    display_name: str = Field(..., description="Human-readable name")
    detection: StackDetectionConfig = Field(default_factory=StackDetectionConfig)
    skills: list[str] = Field(default_factory=list, description="Skill names to load for this stack")
    preflight: list[str] = Field(default_factory=list, description="Shell commands to validate toolchain before execution")
    toolchain: StackToolchainConfig = Field(default_factory=StackToolchainConfig)
    model_preferences: dict[str, list[str]] = Field(default_factory=dict, description="Optional per-category model overrides")


class DownstreamTaskTemplate(BaseModel):
    """Template for a downstream task generated by the Contract Propagation Engine (LE-6).

    The ``title_template`` and ``goal_template`` support ``{contract_name}``,
    ``{triggering_task_id}``, and (goal only) ``{files}`` format placeholders.
    """
    title_template: str = Field(..., description="Template for downstream task title, e.g. 'Sync TypeScript SDK with updated {contract_name}'")
    stack: str = Field("generic", description="Stack profile for the downstream task, e.g. 'node-ts', 'kotlin-android'")
    goal_template: str = Field(..., description="Template for task goal")
    acceptance_criteria: list[str] = Field(default_factory=list, description="Standard AC checkboxes for the task")


class ContractRuleConfig(BaseModel):
    """Declarative contract mutation rule — maps contract file globs to downstream tasks."""
    name: str = Field(..., description="Canonical rule name, e.g. 'shared-schema', 'openapi-spec'")
    patterns: list[str] = Field(default_factory=list, description="Glob patterns for contract files, e.g. ['packages/shared-schema/**', 'openapi/**']")
    downstream_tasks: list[DownstreamTaskTemplate] = Field(default_factory=list, description="List of tasks to generate upon mutation")


def _default_contract_rules() -> list["ContractRuleConfig"]:
    """Sensible default contract propagation rules (LE-6)."""
    return [
        ContractRuleConfig(
            name="openapi-spec",
            patterns=["openapi/**", "contracts/*.yaml", "contracts/*.json"],
            downstream_tasks=[
                DownstreamTaskTemplate(
                    title_template="Regenerate API client for updated {contract_name}",
                    stack="node-ts",
                    goal_template="Regenerate the API client / SDK to match the modified {contract_name} contract. Files changed: {files}",
                    acceptance_criteria=[
                        "API client regenerated from the modified OpenAPI specification",
                        "Generated types match the new contract shapes",
                        "Build and lint pass for the generated client",
                    ],
                )
            ],
        ),
        ContractRuleConfig(
            name="prisma-schema",
            patterns=["*.prisma", "prisma/**"],
            downstream_tasks=[
                DownstreamTaskTemplate(
                    title_template="Sync Prisma schema migration for {contract_name}",
                    stack="node-ts",
                    goal_template="Generate and apply the Prisma migration matching the modified {contract_name}. Files changed: {files}",
                    acceptance_criteria=[
                        "Prisma migration generated from the updated schema",
                        "Migration applies cleanly against the development database",
                    ],
                )
            ],
        ),
        ContractRuleConfig(
            name="protobuf",
            patterns=["proto/**", "*.proto"],
            downstream_tasks=[
                DownstreamTaskTemplate(
                    title_template="Regenerate gRPC stubs for updated {contract_name}",
                    stack="generic",
                    goal_template="Regenerate the gRPC/protobuf stubs for the modified {contract_name} contract. Files changed: {files}",
                    acceptance_criteria=[
                        "gRPC stubs regenerated for all target languages",
                        "Server and client packages compile against the new stubs",
                    ],
                )
            ],
        ),
        ContractRuleConfig(
            name="shared-schema",
            patterns=["packages/shared-schema/**", "shared/schemas/**"],
            downstream_tasks=[
                DownstreamTaskTemplate(
                    title_template="Propagate shared schema changes for {contract_name}",
                    stack="generic",
                    goal_template="Propagate the modified {contract_name} to all consuming services. Files changed: {files}",
                    acceptance_criteria=[
                        "All consumers of the shared schema are updated",
                        "Cross-service contract tests pass",
                    ],
                )
            ],
        ),
    ]


class SpecArtifactType(str, Enum):
    """Spec artifact kinds governed by the Spec-First Gate (LE-8)."""
    ADR = "adr"
    PRD = "prd"
    CONTRACT = "contract"
    DATA_MODEL = "data_model"


class SpecRequirementRule(BaseModel):
    """Declarative spec requirement rule — maps triggering keywords to required artifacts.

    A rule fires when any ``keywords`` substring appears in the (lowercased) task
    content or approved plan. When fired, the Spec-First Gate (LE-8) requires at
    least one matching artifact under ``target_directories`` to exist in the
    workspace or staged diff before implementation may proceed.
    """
    name: str = Field(..., description="Rule name, e.g. 'architecture-decision', 'api-contract'")
    keywords: list[str] = Field(default_factory=list, description="Keywords in task or plan triggering this spec requirement")
    required_artifacts: list[SpecArtifactType] = Field(default_factory=list, description="Artifact types required by this rule")
    target_directories: list[str] = Field(default_factory=list, description="Directory globs where artifacts are expected, e.g. ['docs/adr/**', 'contracts/**']")


class SpecGateConfig(BaseModel):
    """Spec-First Gate configuration (LE-8)."""
    enabled: bool = Field(True, description="Whether the spec-first gate is enforced")
    rules: list[SpecRequirementRule] = Field(default_factory=list, description="Configured spec requirement rules")


def _default_spec_rules() -> list[SpecRequirementRule]:
    """Sensible default spec requirement rules (LE-8).

    Kept as a free function (mirroring ``_default_contract_rules``) so callers can
    wire the defaults explicitly into ``SpecGateConfig.rules`` — the schema default
    is an empty list so the gate is inert until configured.
    """
    return [
        SpecRequirementRule(
            name="architecture-decision",
            keywords=["architecture", "architectural", "redesign", "adr"],
            required_artifacts=[SpecArtifactType.ADR],
            target_directories=["docs/adr/**", "docs/architecture.md"],
        ),
        SpecRequirementRule(
            name="api-contract",
            keywords=["api contract", "openapi", "new endpoint", "graphql schema", "grpc proto"],
            required_artifacts=[SpecArtifactType.CONTRACT],
            target_directories=["contracts/**", "openapi/**", "proto/**"],
        ),
        SpecRequirementRule(
            name="database-schema",
            keywords=["database schema", "prisma migration", "sql migration", "new table", "data model"],
            required_artifacts=[SpecArtifactType.DATA_MODEL],
            target_directories=["docs/data_model.md", "prisma/**", "migrations/**"],
        ),
    ]


class LoopEngineConfig(BaseModel):
    """Root configuration — loop-engine.jsonc."""
    # Providers
    default_provider: str = "gemini/gemini-2.5-flash"
    categories: dict[str, CategoryConfig] = Field(default_factory=lambda: {
        "quick": CategoryConfig(
            models=["kimi/kimi-k3"],
            description="Single-file changes, typos, quick fixes"
        ),
        "deep": CategoryConfig(
            models=["openai/gpt-5.6-sol", "gemini/gemini-2.5-pro"],
            reasoning="medium",
            description="Autonomous research + execution"
        ),
        "visual": CategoryConfig(
            models=["anthropic/claude-opus-5", "kimi/kimi-k3"],
            reasoning="max",
            description="Frontend, UI/UX, design"
        ),
        "unspecified": CategoryConfig(
            models=["gemini/gemini-2.5-flash", "kimi/kimi-k3"],
            description="Default — anything not matched"
        ),
    })
    provider_concurrency: ProviderConcurrency = Field(default_factory=ProviderConcurrency)

    # Executor
    max_parallel_tasks: int = Field(1, ge=1, le=4, description="Max concurrent Hands sessions")
    idle: IdleConfig = Field(default_factory=IdleConfig)

    # Approval
    approval: ApprovalConfig

    # QA
    max_qa_retries: int = Field(3, ge=1, le=10)
    evidence_dir: str = "loop-engine/evidence"

    # Task Entry Trigger Gate
    trigger_mode: Literal["telegram_button", "command_only", "auto"] = Field(
        "telegram_button",
        description="How tasks enter the execution loop: "
                    "'telegram_button' = admin taps Start in Telegram; "
                    "'command_only' = admin runs /run <id>; "
                    "'auto' = legacy auto-pickup on file detection."
    )
    auto_start_on_boot: bool = Field(
        False,
        description="If True, existing backlog tasks run immediately on daemon boot. "
                    "If False, they are registered as PENDING_TRIGGER and await admin action."
    )

    # Paths
    system_prompt_path: str = "system-prompt.md"
    tasks_dir: str = "tasks"
    agmd_path: str = "AGENTS.md"
    conventions_path: str = "docs/conventions.md"

    # Stack Profiles
    stacks_dir: str = Field("stacks", description="Directory containing stack profile YAML/JSON definitions")
    default_stack: str = Field("generic", description="Fallback stack when detection finds no match")

    # Contract Propagation (LE-6)
    contract_rules: list[ContractRuleConfig] = Field(
        default_factory=_default_contract_rules,
        description="Declarative rules mapping contract file mutations to downstream task generators",
    )

    # Spec-First Artifact Gate (LE-8)
    spec_gate: SpecGateConfig = Field(
        default_factory=SpecGateConfig,
        description="Spec-first artifact governance: fail-fast gate requiring spec artifacts before implementation",
    )
